### PR TITLE
add gh actions + fix #37

### LINKED ISSUE #37: Installation fails with R-devel
[R-devel has deprecated the CXXCPP flags](https://cran.r-project.org/bin/windows/base/old/3.6.2/NEWS.R-3.6.2.html).

> Support in R CMD config for F77, FCPIFCPLAGS, CPP, CXXCPP and CXX98 and similar is deprecated. (CPP is found from the system make and may well not be set.)
>
> Use $CC -E and $CXX -E instead of CPP and CXXCPP.

As a consequence, the rcbc package will not install on R-devel and throws the following error (see [here for full log file](https://github.com/prioritizr/prioritizr/runs/1976669271?check_suite_focus=true)):

```
2021-02-25T06:28:12.4819365Z Downloading GitHub repo dirkschumacher/rcbc@HEAD
2021-02-25T06:28:15.0031698Z 
2021-02-25T06:28:15.2400222Z   
2021-02-25T06:28:15.2415310Z    checking for file ‘/tmp/RtmpRW27Ml/remotes41766d8b8a0e/dirkschumacher-rcbc-1c78b0b/DESCRIPTION’ ...
2021-02-25T06:28:15.2498198Z   
2021-02-25T06:28:15.2500340Z ✔  checking for file ‘/tmp/RtmpRW27Ml/remotes41766d8b8a0e/dirkschumacher-rcbc-1c78b0b/DESCRIPTION’
2021-02-25T06:28:15.2560005Z 
2021-02-25T06:28:15.2592458Z   
2021-02-25T06:28:15.2594754Z ─  preparing ‘rcbc’:
2021-02-25T06:28:15.2605134Z 
2021-02-25T06:28:15.2607323Z   
2021-02-25T06:28:15.2691473Z    checking DESCRIPTION meta-information ...
2021-02-25T06:28:15.2725028Z   
2021-02-25T06:28:15.2726542Z ✔  checking DESCRIPTION meta-information
2021-02-25T06:28:15.2737390Z 
2021-02-25T06:28:15.2806982Z   
2021-02-25T06:28:15.2808078Z ─  cleaning src
2021-02-25T06:28:15.2809224Z ─  running ‘cleanup’
2021-02-25T06:28:15.3074250Z 
2021-02-25T06:28:15.3127668Z   
2021-02-25T06:28:15.3130293Z ─  checking for LF line-endings in source and make files and shell scripts
2021-02-25T06:28:15.3142181Z 
2021-02-25T06:28:15.3174079Z   
2021-02-25T06:28:15.3176693Z ─  checking for empty or unneeded directories
2021-02-25T06:28:15.3206736Z ─  building ‘rcbc_0.1.0.9001.tar.gz’
2021-02-25T06:28:15.3273515Z 
2021-02-25T06:28:15.3276704Z   
2021-02-25T06:28:15.3278235Z    
2021-02-25T06:28:15.3402756Z Installing package into ‘/home/runner/work/_temp/Library’
2021-02-25T06:28:15.3404019Z (as ‘lib’ is unspecified)
2021-02-25T06:28:15.5712540Z * installing *source* package ‘rcbc’ ...
2021-02-25T06:28:15.5715309Z ** using staged installation
2021-02-25T06:28:15.5893498Z 
2021-02-25T06:28:15.5895644Z Found pkg-config cflags and libs!
2021-02-25T06:28:15.5897074Z Using PKG_CFLAGS=-I/usr/include/coin
2021-02-25T06:28:15.5899445Z Using PKG_LIBS=-lCbcSolver -lCbc -lpthread -lrt -lCgl -lOsiClp -lClpSolver -lClp -lOsi -lCoinUtils -lbz2 -lz -llapack -lblas -lm
2021-02-25T06:28:15.6150251Z 'config' variable 'CXXCPP' is defunct
2021-02-25T06:28:15.6772924Z ------------------------- ANTICONF ERROR ---------------------------
2021-02-25T06:28:15.6773930Z Configuration failed because cbc was not found. Try installing:
2021-02-25T06:28:15.6775395Z  * deb: coinor-libcbc-dev, coinor-libclp-dev (Debian, Ubuntu, etc)
2021-02-25T06:28:15.6776607Z  * rpm: coin-or-Cbc-devel, coin-or-Clp-devel (Fedora, CentOS, RHEL)
2021-02-25T06:28:15.6777606Z  * brew: coin-or-tools/coinor/cbc (Mac OSX)
2021-02-25T06:28:15.6779209Z If cbc is already installed, check that 'pkg-config' is in your
2021-02-25T06:28:15.6780310Z PATH and PKG_CONFIG_PATH contains a cbc.pc file. If pkg-config
2021-02-25T06:28:15.6781241Z is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
2021-02-25T06:28:15.6782494Z R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
2021-02-25T06:28:15.6783683Z --------------------------------------------------------------------
2021-02-25T06:28:15.6798414Z ERROR: configuration failed for package ‘rcbc’
2021-02-25T06:28:15.6806126Z * removing ‘/home/runner/work/_temp/Library/rcbc’
```

Note that the specified coin-or dependencies were previously installed:

```
2021-02-25T06:26:32.5042028Z Selecting previously unselected package coinor-libclp-dev.
2021-02-25T06:26:32.5297113Z Preparing to unpack .../08-coinor-libclp-dev_1.17.5+repack1-1_amd64.deb ...
2021-02-25T06:26:32.5312407Z Unpacking coinor-libclp-dev (1.17.5+repack1-1) ...
...
2021-02-25T06:26:32.8135563Z Selecting previously unselected package coinor-libcbc-dev.
2021-02-25T06:26:32.8449195Z Preparing to unpack .../10-coinor-libcbc-dev_2.10.3+repack1-1build1_amd64.deb ...
2021-02-25T06:26:32.8462032Z Unpacking coinor-libcbc-dev (2.10.3+repack1-1build1) ...
```

Would it be possible to update the rcbc package so that it is compatible with future versions of R? If it would be helpful, I would be happy to look into submitting a PR to fix this issue?

### PR DESCRIPTION
**Pull request by jeffreyhanson**
As discussed over email, this PR adds (1) GitHub Action workflows for CI testing (for [Ubuntu](https://github.com/jeffreyhanson/rcbc/actions/runs/612572990), [Mac](https://github.com/jeffreyhanson/rcbc/actions/runs/612572989), and [Windows](https://github.com/jeffreyhanson/rcbc/actions/runs/612572991)), (2) workflow for documentation, and (3) fixes the R-devel issues (per #37). It also includes adding a system file to .gitignore (i.e. `.directory` -- the Kubuntu file manager file manager creates these when I view files on my laptop) to help make it easier for me to contribute to this repo. Please let me know if you have any questions?

Please note that the Windows CI builds are failing, likely due to issues discussed in https://github.com/dirkschumacher/rcbc/issues/34. I will try to investigate that issue next to see if I can help?

### CODE REVIEW

**Comment by dirkschumacher** [comment]
Thanks!

**Comment by dirkschumacher** [comment]
Investigating #34 would be great.

**Comment by dirkschumacher** [comment]
Oh no 🙈, seems we forgot to build the readme.

**Comment by dirkschumacher** [comment]
Nice, that is done automatically

**Comment by jeffreyhanson** [comment]
Awesome - thanks! I'll start working on the next issue.

**Pull request merged**
