### PR TITLE
More documentation updates

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR contains some more documentation improvements. Specifically, it contains the following changes:

1. Adds a CITATION file. Note that Bulat Yapparov is absent from this file because they are not listed in the current package citation per `citation("rcbc")` -- happy to fix this if that's wrong though?
2. Fixes a couple of typos in the vignette (sorry for not catching those earlier)
3. Updates the README
4. Removes the junk `.github/depends.Rds` (sorry for not correctly addressing this in the previous PR).
5. Updates RcppExports (this was automatically done with `devtools::load_all()`).

@dirkschumacher, please let me know if there's anything I can do to help?

### CODE REVIEW

**Comment by dirkschumacher** [comment]
Thanks. Looks good to me. @byapparov you also contributed quite a bit to the package and I think it would be appropriate to also have your role as "aut". Let me know if that is ok.

**Comment by dirkschumacher** [comment]
Thanks @jeffreyhanson for all your work!

**Comment by jeffreyhanson** [comment]
No worries @dirkschumacher - I'm happy to help out! What else can I do to help get this ready for CRAN?

**Comment by byapparov** [comment]
@dirkschumacher would be my honer to be in aut, thanks )

**Pull request merged**
